# Generated by Django 4.1.1 on 2023-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("u_auth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="Address",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Destrict",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Mobile",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="Mobile2",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
