# Generated by Django 4.1.1 on 2023-04-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("u_auth", "0002_user_address_user_destrict_user_mobile_user_mobile2"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="Destrict",
            new_name="Center1",
        ),
        migrations.AddField(
            model_name="user",
            name="Center2",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
