# Generated by Django 4.1.1 on 2023-04-04 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_lead_come_thrue_lead_coordinator_lead_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="Come_Thrue",
            new_name="Lead_Mode",
        ),
        migrations.AddField(
            model_name="lead",
            name="Lead_Mode_Text",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
