# Generated by Django 4.1.1 on 2023-04-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0003_rename_come_thrue_lead_lead_mode_lead_lead_mode_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="Lead_Mode_Text",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
