# Generated by Django 4.1.1 on 2023-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0004_alter_lead_lead_mode_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Full_Name", models.CharField(max_length=50)),
                ("Street_Address", models.CharField(max_length=100, null=True)),
                ("City", models.CharField(max_length=50, null=True)),
                ("State", models.CharField(max_length=50, null=True)),
                ("Zip_Code", models.CharField(max_length=50, null=True)),
                ("Phone", models.CharField(max_length=15, null=True)),
                ("Email", models.EmailField(max_length=254, null=True)),
                ("Guardian_Name", models.CharField(max_length=50)),
                ("Guardian_Mobile", models.CharField(max_length=15)),
                ("Adhar", models.BooleanField(default=False)),
                ("Passport", models.BooleanField(default=False)),
                ("Date_Of_Birth", models.DateField()),
                ("Age_4_13", models.BooleanField(default=False)),
                ("Age_14_17", models.BooleanField(default=False)),
                ("Preferred_Location", models.CharField(max_length=50, null=True)),
                ("Travel_Mode", models.CharField(max_length=50, null=True)),
                ("Playing_Position", models.CharField(max_length=50)),
                ("School_Name", models.CharField(max_length=75, null=True)),
                ("School_Address", models.CharField(max_length=100, null=True)),
                ("Study_Standard", models.IntegerField(null=True)),
                ("Study_Devision", models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
