# Generated by Django 4.1.1 on 2023-04-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0007_remove_students_adhar_remove_students_age_14_17_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reference", models.CharField(max_length=15)),
                ("Name", models.CharField(max_length=50)),
            ],
        ),
    ]
