# Generated by Django 4.1.1 on 2023-04-06 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0012_alter_lead_coordinator"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="Center",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Core.center",
            ),
        ),
    ]
