# Generated by Django 4.1.1 on 2023-04-06 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0013_students_center"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead_Updates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                ("Description", models.TextField()),
                (
                    "Lead",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.lead",
                    ),
                ),
            ],
        ),
    ]
