# Generated by Django 4.1.1 on 2023-04-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0015_lead_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                ("From_Time", models.TimeField()),
                ("To_Time", models.TimeField()),
                (
                    "Center",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Core.center",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attandance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Attandance", models.BooleanField(default=False)),
                (
                    "Section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Core.section",
                    ),
                ),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="Core.students",
                    ),
                ),
            ],
        ),
    ]
