# Generated by Django 4.1.1 on 2023-04-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0016_section_attandance"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="Reference",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
