# Generated by Django 4.1.1 on 2023-04-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0017_section_reference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attandance",
            name="Attandance",
            field=models.CharField(default="Absent", max_length=15),
        ),
    ]
