# Generated by Django 4.1.1 on 2023-04-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0018_alter_attandance_attandance"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="Ended",
            field=models.BooleanField(default=False),
        ),
    ]
