# Generated by Django 4.1.1 on 2023-04-07 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Core", "0019_section_ended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="User",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
