# Generated by Django 4.1.1 on 2023-04-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0022_alter_coordinator_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="Location",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
