# Generated by Django 4.1.1 on 2023-04-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0023_center_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="Address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
